version: '3.9'

services:
  web:
    build: .
    command: sh -c "pip --version && pip install --upgrade pip && python manage.py makemigrations && python manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=SzX3!2#^5!4GcH6$$2FvBhJ7%%$$-3u#a2g7q)w^5vwgoem@28m$$__4wii4$$u#ee5x74zk8*jd1ifle"

  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
